### ISSUE TITLE
Determine number of cloud run jobs

### ISSUE THREAD

**Issue by steveoh** [agrc/udot-parcel-ml#17]
We'll need to review the time taken values in the logs to see roughly how many images can be processed in the default 10min timeout to estimate how many jobs we'll need to create for 90k files.

**Comment by eneemann** [comment]
From what I'm seeing on the 10 jobs run yesterday, they took an average of 1.923 min to complete with about 8 files each (79 total files).

- roughly 2 min for 8 files = 4 files per min or 0.25 min per file
  - For 10-minute jobs:
    - each 10 min job could process about 5*8 = 40 files
    - this would require about 90,000/40 = **_2,250 jobs_** 
  - For 100 jobs:
    - or if 100 jobs for 90k files, that would be 900 files per job
    - 900/4 (files per minute) = **_225 min per job_**
