### ISSUE TITLE
investigate why some images find no circles

### ISSUE THREAD

**Issue by steveoh** [agrc/udot-parcel-ml#18]
this can be a running list

- production6/S-0154(51)13_RW-15 AERIAL__Rev-6.JPG  (7 circles of interest)
- production6/S-0154(51)13_RW-14 AERIAL__Rev-3.JPG (2 circles of interest)
- rich/F-108(11)_04_Typical_Rev-1.tiff (0 circles of interest)
- rich/F-108(11)_01A_Title_Rev-1.tiff (0 circles of interest)
- rich/F-108(9)_HF08_Plan & Profile.tiff (0 circles of interest)
- rich/FAP -108-A_HF-03_Plan & Profile.tif (0 circles of interest)
- rich/F-108(9)_HF10_Plan & Profile.tif (0 circles of interest)
- rich/FAP -108-A_HF-02_Typical.tif (0 circles of interest)
- rich/F-108(9)_HF09_Plan & Profile.tif (0 circles of interest)
- rich/FAP -108-A_HF-01_Title.tif (0 circles of interest)
- archive3/F-I215(157)27 Kilgore Accident Prevention Plan.pdf (0 circles of interest)
- rich/F-108(9)_HF15_Plan & Profile_1.tif (0 circles of interest)
- rich/FAP -108-D(1)_HF-04_Plan & Profile.TIF (0 circles of interest)
- rich/F-108(9)_HF07_Plan & Profile.tif (0 circles of interest)
- rich/F-108(9)_HF14_Plan & Profile.tif (0 circles of interest)
- rich/FAP -108-D(1)_HF-03_Plan & Profile.TIF (0 circles of interest)
- rich/F-108(9)_HF06_Plan & Profile.tif (0 circles of interest)
- rich/F-108(9)_HF13_Plan & Profile.tif (0 circles of interest)
- rich/F-108(9)_HF02_Typical.tif (0 circles of interest)
- rich/FAP -108-D(1)_HF-02_Typical.TIF (0 circles of interest)

**Comment by eneemann** [comment]
> * production6/S-0154(51)13_RW-14 AERIAL__Rev-3.JPG - i counted at least 15
I think only about 7 of these are legitimate, the ones in the 7800 range.  The others are too small/not of interest. I believe those are related to curve information.

**Comment by eneemann** [comment]
Generally speaking, I think most of the "no circles detected" images are cruft.  From what I've glanced at so far they are profiles, title documents, accident plans, etc.
